name: CreateBranchWorkflow

on:
  create:
    branches:
    - '!documentation/**'

jobs:
  provision:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1

    - name: Run a multi-line script
      run: |
        echo Running on branch creation, branch: ${BRANCH_NAME}
        echo Create an s3 bucket ${BRANCH_NAME} here...
