name: DeleteBranchWorkflow

on:
  delete:
    branches:
    - '!documentation/**'

env:
  AWS_REGION: us-east-1
  BRANCH_NAME: ${{ github.event.ref }}

jobs:
  delete:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: remove bucket
      run: |
        echo "Running on branch deletion, branch: ${env.BRANCH_NAME}"
        echo "Event ref and ref_type: ${{ github.event.ref }} - ${{ github.event.ref_type }}"
        aws --version
        aws iam get-user
        echo "Delete an s3 bucket ${env.BRANCH_NAME} here..."
        ./.github/scripts/remove-bucket.sh ${env.BRANCH_NAME}.branchexample.flexion.us ${AWS_REGION}
        echo "Removing the paramenter that indicates the infrastructure is deployed..."
        aws ssm delete-parameter --name "${env.BRANCH_NAME}"
