name: DeleteBranchWorkflow

on:
  delete:
    branches:
    - '!documentation/**'

env:
  AWS_REGION: us-east-1

jobs:
  delete:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: remove bucket
      run: |
        echo "Running on branch deletion, branch: ${BRANCH_NAME}"
        aws --version
        aws iam get-user
        echo "Delete an s3 bucket ${BRANCH_NAME} here..."
        ./.github/scripts/remove-bucket.sh ${BRANCH_NAME}.branchexample.flexion.us ${AWS_REGION}
        echo "Removing the paramenter that indicates the infrastructure is deployed..."
        aws ssm delete-parameter --name "${BRANCH_NAME}"
