name: PushBranchWorkflow

on:
  push:
    branches:
    - '!documentation/**'
    - '*'

env:
  AWS_REGION: us-east-1

jobs:
  confirm-prerequisites:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        python-version: '3.x' 

    - name: Confirm prerequisites are in place to deploy
      run: |
        echo "Checking prerequisties are in place to deploy branch: ${BRANCH_NAME}"
        python -c "import sys; print(sys.version)"
        aws --version
        aws iam get-user
        ./.github/scripts/wait-for-param.sh ${BRANCH_NAME}
        echo "Update the app for ${BRANCH_NAME} here..."
        python -m pip install --upgrade pip
        if [ -f .github/requirements.txt ]; then pip install -r .github/requirements.txt; fi

    - name: Deploy the application
      if: ${{ success() }}
      run: |
        echo "Running on branch push, branch: ${BRANCH_NAME}"
        aws --version
        aws iam get-user
        echo "Event ref and ref_type: ${{ github.event.ref }} - ${{ github.event.ref_type }}"
        echo "Update the app for ${BRANCH_NAME} here..."
        aws s3 cp app/index.html s3://${BRANCH_NAME}.branchexample.flexion.us/index.html

    - name: Release the deploy lock
      if: ${{ always() }}
      run: |
        echo "Running on branch push, branch: ${BRANCH_NAME}"
