name: CreateBranchWorkflow

on:
  create:
    branches:
    - '!documentation/**'

jobs:
  provision:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run a multi-line script
      run: |
        echo "Running on branch creation, branch: ${BRANCH_NAME}"
        aws --version
        aws iam get-user
        echo "Creating the parameter to specify infrastructure creation is complete for ${BRANCH_NAME}"
        aws ssm put-parameter --name "${BRANCH_NAME}" -value "provisioned" --type String
        echo Create an s3 bucket ${BRANCH_NAME} here...
